/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Home/Banner.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    FoodCategory: typeof import('./src/components/Home/FoodCategory.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeHeader: typeof import('./src/components/Home/HomeHeader.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IIcOutlineLocationOn: typeof import('~icons/ic/outline-location-on')['default']
    IIcRoundPerson: typeof import('~icons/ic/round-person')['default']
    IMaterialSymbolsFilterAltOffOutlineRounded: typeof import('~icons/material-symbols/filter-alt-off-outline-rounded')['default']
    IMaterialSymbolsHouse: typeof import('~icons/material-symbols/house')['default']
    IMaterialSymbolsHouseRounded: typeof import('~icons/material-symbols/house-rounded')['default']
    IMaterialSymbolsLocationOnOutline: typeof import('~icons/material-symbols/location-on-outline')['default']
    IMaterialSymbolsTextSnippetOutlineSharp: typeof import('~icons/material-symbols/text-snippet-outline-sharp')['default']
    IOcticonTriangleDown24: typeof import('~icons/octicon/triangle-down24')['default']
    IPhMagnifyingGlassBold: typeof import('~icons/ph/magnifying-glass-bold')['default']
    ITdesignCompass: typeof import('~icons/tdesign/compass')['default']
    Recommend: typeof import('./src/components/Home/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Home/Search.vue')['default']
    SuperMember: typeof import('./src/components/Home/SuperMember.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
