/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/home/Banner.vue')['default']
    BusinessInfoHeader: typeof import('./src/components/businessInfo/BusinessInfoHeader.vue')['default']
    BusinessListHeader: typeof import('./src/components/businessList/BusinessListHeader.vue')['default']
    Cart: typeof import('./src/components/businessInfo/Cart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    FoodCategory: typeof import('./src/components/home/FoodCategory.vue')['default']
    FoodList: typeof import('./src/components/businessInfo/FoodList.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    IIcRoundPerson: typeof import('~icons/ic/round-person')['default']
    IMaterialSymbolsHouseRounded: typeof import('~icons/material-symbols/house-rounded')['default']
    IMaterialSymbolsTextSnippetOutlineSharp: typeof import('~icons/material-symbols/text-snippet-outline-sharp')['default']
    ITdesignCompass: typeof import('~icons/tdesign/compass')['default']
    MineHeader: typeof import('./src/components/mine/MineHeader.vue')['default']
    OrderAddress: typeof import('./src/components/order/OrderAddress.vue')['default']
    OrderHeader: typeof import('./src/components/order/OrderHeader.vue')['default']
    OrderListHeader: typeof import('./src/components/orderList/orderListHeader.vue')['default']
    PaymentHead: typeof import('./src/components/payment/PaymentHead.vue')['default']
    Recommend: typeof import('./src/components/home/Recommend.vue')['default']
    RecommendBusiness: typeof import('./src/components/home/RecommendBusiness.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/home/Search.vue')['default']
    SuperMember: typeof import('./src/components/home/SuperMember.vue')['default']
  }
}
